services:
  control:
    container_name: ${PROBE_PREFIX}mtr-control
    hostname: ${PROBE_PREFIX}mtr-control
  
  probe1:
    container_name: ${PROBE_PREFIX}mtr-probe1
    hostname: ${PROBE_PREFIX}mtr-probe1
  
  probe2:
    container_name: ${PROBE_PREFIX}mtr-probe2
    hostname: ${PROBE_PREFIX}mtr-probe2
  
  probe3:
    container_name: ${PROBE_PREFIX}mtr-probe3
    hostname: ${PROBE_PREFIX}mtr-probe3     
  
  probe4:
    container_name: ${PROBE_PREFIX}mtr-probe4
    hostname: ${PROBE_PREFIX}mtr-probe4
  
  probe5:
    container_name: ${PROBE_PREFIX}mtr-probe5
    hostname: ${PROBE_PREFIX}mtr-probe5
