services:
  control:
    build:
      context: .
      dockerfile: Dockerfile.control
    profiles: ["all", "remove", "1", "2", "3", "4", "5"]
    container_name: mtr-control
    hostname: mtr-control
    image: mtr-control:latest
    volumes:
      - mtr-client:/config
    networks:
      mtr-client:
    restart: unless-stopped

  probe1:
    build:
      context: .
      dockerfile: Dockerfile.probe
    profiles: ["all", "remove", "1", "2", "3", "4", "5"]
    depends_on:
      - control
    container_name: mtr-probe1
    hostname: mtr-probe1
    image: mtr-probe:latest
    environment:
      - PROBE_SOURCE=${PROBE_SOURCE}
    volumes:
      - mtr-client:/config
    networks:
      mtr-client:
    restart: unless-stopped

  probe2:
    profiles: ["all", "remove", "2", "3", "4", "5"]
    depends_on:
      - control
    container_name: mtr-probe2
    hostname: mtr-probe2
    image: mtr-probe:latest
    environment:
      - PROBE_SOURCE=${PROBE_SOURCE}
    volumes:
      - mtr-client:/config
    networks:
      mtr-client:
    restart: unless-stopped

  probe3:
    profiles: ["all", "remove", "3", "4", "5"]
    depends_on:
      - control
    container_name: mtr-probe3
    hostname: mtr-probe3
    image: mtr-probe:latest
    environment:
      - PROBE_SOURCE=${PROBE_SOURCE}
    volumes:
      - mtr-client:/config
    networks:
      mtr-client:
    restart: unless-stopped

  probe4:
    profiles: ["all", "remove", "4", "5"]
    depends_on:
      - control
    container_name: mtr-probe4
    hostname: mtr-probe4
    image: mtr-probe:latest
    environment:
      - PROBE_SOURCE=${PROBE_SOURCE}
    volumes:
      - mtr-client:/config
    networks:
      mtr-client:
    restart: unless-stopped

  probe5:
    profiles: ["all", "remove", "5"]
    depends_on:
      - control
    container_name: mtr-probe5
    hostname: mtr-probe5
    image: mtr-probe:latest
    environment:
      - PROBE_SOURCE=${PROBE_SOURCE}
    volumes:
      - mtr-client:/config
    networks:
      mtr-client:
    restart: unless-stopped

networks:
  mtr-client:
    driver: bridge

volumes:
  mtr-client:
